export const languages = [
    {
        "resourceId": "862249c19aad",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "English",
        "code": "0",
        "description": "EN",
        "orderNumber": 1,
        "isoCode": "en-GB",
        "isoFriendlyName": "English (United Kingdom)"
    },
    {
        "resourceId": "8199a5d7a850",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Turkish",
        "code": "1",
        "description": "TR",
        "orderNumber": 2,
        "isoCode": "tr-TR",
        "isoFriendlyName": "Turkish (Turkey)"
    },
    {
        "resourceId": "753ddb1b0263",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "French",
        "code": "2",
        "description": "FR",
        "orderNumber": 3,
        "isoCode": "fr-FR",
        "isoFriendlyName": "French (France)"
    },
    {
        "resourceId": "280faa1981b6",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Arabic",
        "code": "3",
        "description": "AR",
        "orderNumber": 4,
        "isoCode": "ar-SA",
        "isoFriendlyName": "Arabic (Saudi Arabia)"
    },
    {
        "resourceId": "c59e929f683d",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Chinese",
        "code": "4",
        "description": "CN",
        "orderNumber": 5,
        "isoCode": "zh-CN",
        "isoFriendlyName": "Chinese (China)"
    },
    {
        "resourceId": "505ad3e87702",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Russian",
        "code": "5",
        "description": "RU",
        "orderNumber": 6,
        "isoCode": "ru-RU",
        "isoFriendlyName": "Russian (Russia)"
    },
    {
        "resourceId": "b4e6bae3fdc2",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "German",
        "code": "6",
        "description": "DE",
        "orderNumber": 7,
        "isoCode": "de-DE",
        "isoFriendlyName": "German (Germany)"
    },
    {
        "resourceId": "dFHlHPFhr2dS",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Burmese",
        "code": "7",
        "description": "MY",
        "orderNumber": 8,
        "isoCode": "my-MM",
        "isoFriendlyName": "Burmese (Myanmar)"
    },
    {
        "resourceId": "YEt10nsuEb6F",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Czech",
        "code": "8",
        "description": "CS",
        "orderNumber": 9,
        "isoCode": "cs-CZ",
        "isoFriendlyName": "Czech (Czech Republic)"
    },
    {
        "resourceId": "eD1mnvAWmPRS",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Danish",
        "code": "9",
        "description": "DA",
        "orderNumber": 10,
        "isoCode": "da-DK",
        "isoFriendlyName": "Danish (Denmark)"
    },
    {
        "resourceId": "m3d7p3M6rDGB",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Dutch",
        "code": "10",
        "description": "NL",
        "orderNumber": 11,
        "isoCode": "nl-NL",
        "isoFriendlyName": "Dutch (The Netherlands)"
    },
    {
        "resourceId": "vb7SFRKHgF1r",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Finnish",
        "code": "11",
        "description": "FI",
        "orderNumber": 12,
        "isoCode": "fi-FI",
        "isoFriendlyName": "Finnish (Finland)"
    },
    {
        "resourceId": "bkAbw5LzrreS",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Greek",
        "code": "12",
        "description": "EL",
        "orderNumber": 13,
        "isoCode": "el-GR",
        "isoFriendlyName": "Greek (Greece)"
    },
    {
        "resourceId": "bCH3NneVEajv",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Hebrew",
        "code": "13",
        "description": "HE",
        "orderNumber": 14,
        "isoCode": "he-IL",
        "isoFriendlyName": "Hebrew (Israel)"
    },
    {
        "resourceId": "WDEKFW1wgH8S",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Hindi (India)",
        "code": "14",
        "description": "HI",
        "orderNumber": 15,
        "isoCode": "hi-IN",
        "isoFriendlyName": "Hindi (India)"
    },
    {
        "resourceId": "lVUjVkY2pc3j",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Hungarian",
        "code": "15",
        "description": "HU",
        "orderNumber": 16,
        "isoCode": "hu-HU",
        "isoFriendlyName": "Hungarian (Hungary)"
    },
    {
        "resourceId": "6V9VP3aZZxlc",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Indonesian",
        "code": "16",
        "description": "ID",
        "orderNumber": 17,
        "isoCode": "id-ID",
        "isoFriendlyName": "Indonesian (Indonesia)"
    },
    {
        "resourceId": "hdybua8Cv4ec",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Italian",
        "code": "17",
        "description": "IT",
        "orderNumber": 18,
        "isoCode": "it-IT",
        "isoFriendlyName": "Italian (Italy)"
    },
    {
        "resourceId": "P8ERzX721bew",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Japanese",
        "code": "18",
        "description": "JA",
        "orderNumber": 19,
        "isoCode": "ja-JP",
        "isoFriendlyName": "Japanese (Japan)"
    },
    {
        "resourceId": "SSKP8Cu0RwMe",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Korean",
        "code": "19",
        "description": "KO",
        "orderNumber": 20,
        "isoCode": "ko-KR",
        "isoFriendlyName": "Korean (Republic of Korea)"
    },
    {
        "resourceId": "hNEhVEH7xrBr",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Malay (Malaysia)",
        "code": "20",
        "description": "MS",
        "orderNumber": 21,
        "isoCode": "ms-MY",
        "isoFriendlyName": "Malay (Malaysia)"
    },
    {
        "resourceId": "Tu6td3gAcblg",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Norwegian",
        "code": "21",
        "description": "NO",
        "orderNumber": 22,
        "isoCode": "no-NO",
        "isoFriendlyName": "Norwegian (Norway)"
    },
    {
        "resourceId": "xXUZKXnWZ7rS",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Polish",
        "code": "22",
        "description": "PL",
        "orderNumber": 23,
        "isoCode": "pl-PL",
        "isoFriendlyName": "Polish (Poland)"
    },
    {
        "resourceId": "uTMbJvE91lW0",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Portuguese",
        "code": "23",
        "description": "PT",
        "orderNumber": 24,
        "isoCode": "pt-PT",
        "isoFriendlyName": "Portuguese (Portugal)"
    },
    {
        "resourceId": "VPN9T0ChSlye",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Romanian",
        "code": "24",
        "description": "RO",
        "orderNumber": 25,
        "isoCode": "ro-RO",
        "isoFriendlyName": "Romanian (Romania)"
    },
    {
        "resourceId": "0ljMMafV3vGT",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Spanish",
        "code": "25",
        "description": "ES",
        "orderNumber": 26,
        "isoCode": "es-ES",
        "isoFriendlyName": "Spanish (Spain)"
    },
    {
        "resourceId": "nJ2SpB4rCZpb",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Swahili",
        "code": "26",
        "description": "SW",
        "orderNumber": 27,
        "isoCode": "sw-KE",
        "isoFriendlyName": "Swahili (Kenya)"
    },
    {
        "resourceId": "3vg9Fml7TG4r",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Swedish",
        "code": "27",
        "description": "SV",
        "orderNumber": 28,
        "isoCode": "sv-SE",
        "isoFriendlyName": "Swedish (Sweden)"
    },
    {
        "resourceId": "Rpa4rjtVlWXp",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Thai",
        "code": "28",
        "description": "TH",
        "orderNumber": 29,
        "isoCode": "th-TH",
        "isoFriendlyName": "Thai (Thailand)"
    },
    {
        "resourceId": "19MCUWGHV65H",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Ukrainian",
        "code": "29",
        "description": "UK",
        "orderNumber": 30,
        "isoCode": "uk-UA",
        "isoFriendlyName": "Ukrainian (Ukraine)"
    },
    {
        "resourceId": "D9nZwFgL5MAV",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Vietnamese",
        "code": "30",
        "description": "VI",
        "orderNumber": 31,
        "isoCode": "vi-VN",
        "isoFriendlyName": "Vietnamese (Vietnam)"
    },
    {
        "resourceId": "PPfbzbZhdHbS",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Azerbaijani",
        "code": "31",
        "description": "AZ",
        "orderNumber": 32,
        "isoCode": "az-AZ",
        "isoFriendlyName": "Azerbaijani (Azerbaijan)"
    },
    {
        "resourceId": "0hFUsAVjRjdy",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Urdu",
        "code": "32",
        "description": "UR",
        "orderNumber": 33,
        "isoCode": "ur-PK",
        "isoFriendlyName": "Urdu (Pakistan)"
    },
    {
        "resourceId": "XJu1UmaF9CWs",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Tajik",
        "code": "33",
        "description": "TG",
        "orderNumber": 34,
        "isoCode": "tg-TJ",
        "isoFriendlyName": "Tajik (Tajikistan)"
    },
    {
        "resourceId": "unk9hfHg5wls",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Turkmen",
        "code": "34",
        "description": "TK",
        "orderNumber": 35,
        "isoCode": "tk-TM",
        "isoFriendlyName": "Turkmen (Turkmenistan)"
    },
    {
        "resourceId": "Ej0JlznC9uRB",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Bengali",
        "code": "35",
        "description": "BN",
        "orderNumber": 36,
        "isoCode": "bn-BD",
        "isoFriendlyName": "Bengali (Bangladesh)"
    },
    {
        "resourceId": "Yjgc7HMFxPEJ",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Kyrgyz",
        "code": "36",
        "description": "KY",
        "orderNumber": 37,
        "isoCode": "ky-KG",
        "isoFriendlyName": "Kyrgyz (Kyrgyzstan)"
    },
    {
        "resourceId": "7bA2baC4S0DX",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Uzbek",
        "code": "37",
        "description": "UZ",
        "orderNumber": 38,
        "isoCode": "uz-UZ",
        "isoFriendlyName": "Uzbek (Uzbekistan)"
    },
    {
        "resourceId": "EleGkhfsNTDp",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Kazakh",
        "code": "38",
        "description": "KK",
        "orderNumber": 39,
        "isoCode": "kk-KZ",
        "isoFriendlyName": "Kazakh (Kazakhstan)"
    },
    {
        "resourceId": "yatc1pTacKz5",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Croatian",
        "code": "39",
        "description": "HR",
        "orderNumber": 40,
        "isoCode": "hr-HR",
        "isoFriendlyName": "Croatian (Croatia)"
    },
    {
        "resourceId": "4FKL25Uttszs",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Slovene",
        "code": "40",
        "description": "SI",
        "orderNumber": 41,
        "isoCode": "sl-SI",
        "isoFriendlyName": "Slovene (Slovenia)"
    },
    {
        "resourceId": "dHEGFvyZm3ME",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Slovak",
        "code": "41",
        "description": "SK",
        "orderNumber": 42,
        "isoCode": "sk-SK",
        "isoFriendlyName": "Slovak (Slovakia)"
    },
    {
        "resourceId": "bmeKAb2HbCuZ",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Albanian",
        "code": "42",
        "description": "SQ",
        "orderNumber": 43,
        "isoCode": "sq-AL",
        "isoFriendlyName": "Albanian (Albania)"
    },
    {
        "resourceId": "mB9192u7HZBx",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Georgian",
        "code": "43",
        "description": "KA",
        "orderNumber": 44,
        "isoCode": "ka-GE",
        "isoFriendlyName": "Georgian (Georgia)"
    },
    {
        "resourceId": "eMkYbRPv3gS6",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Tagalog",
        "code": "44",
        "description": "TGL",
        "orderNumber": 45,
        "isoCode": "tl-PH",
        "isoFriendlyName": "Tagalog (Philippines)"
    },
    {
        "resourceId": "nzKDnAbdELkb",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Punjabi",
        "code": "45",
        "description": "PA",
        "orderNumber": 46,
        "isoCode": "pa-IN",
        "isoFriendlyName": "Punjabi (India)"
    },
    {
        "resourceId": "8c275537dffa",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Bengali (India)",
        "code": "46",
        "description": "BN-IN",
        "orderNumber": 47,
        "isoCode": "bn-IN",
        "isoFriendlyName": "Bengali (India)"
    },
    {
        "resourceId": "30194dc3e9be",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "German (Austria)",
        "code": "47",
        "description": "DE-AT",
        "orderNumber": 48,
        "isoCode": "de-AT",
        "isoFriendlyName": "German (Austria)"
    },
    {
        "resourceId": "787b173958a2",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "German (Switzerland)",
        "code": "48",
        "description": "DE-CH",
        "orderNumber": 49,
        "isoCode": "de-CH",
        "isoFriendlyName": "German (Switzerland)"
    },
    {
        "resourceId": "828ce5983939",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "English (Australia)",
        "code": "49",
        "description": "EN-AU",
        "orderNumber": 50,
        "isoCode": "en-AU",
        "isoFriendlyName": "English (Australia)"
    },
    {
        "resourceId": "789b900f1adf",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "English (Canada)",
        "code": "50",
        "description": "EN-CA",
        "orderNumber": 51,
        "isoCode": "en-CA",
        "isoFriendlyName": "English (Canada)"
    },
    {
        "resourceId": "65c4705fce52",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "English (Ireland)",
        "code": "51",
        "description": "EN-IE",
        "orderNumber": 52,
        "isoCode": "en-IE",
        "isoFriendlyName": "English (Ireland)"
    },
    {
        "resourceId": "4ff4ad93f659",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "English (India)",
        "code": "52",
        "description": "EN-IN",
        "orderNumber": 53,
        "isoCode": "en-IN",
        "isoFriendlyName": "English (India)"
    },
    {
        "resourceId": "15a3134acd4b",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "English (New Zealand)",
        "code": "53",
        "description": "EN-NZ",
        "orderNumber": 54,
        "isoCode": "en-NZ",
        "isoFriendlyName": "English (New Zealand)"
    },
    {
        "resourceId": "edb245e333bf",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "English (United States)",
        "code": "54",
        "description": "EN-US",
        "orderNumber": 55,
        "isoCode": "en-US",
        "isoFriendlyName": "English (United States)"
    },
    {
        "resourceId": "cdcc24c3017b",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "English (South Africa)",
        "code": "55",
        "description": "EN-ZA",
        "orderNumber": 56,
        "isoCode": "en-ZA",
        "isoFriendlyName": "English (South Africa)"
    },
    {
        "resourceId": "fad52584b9e2",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Spanish (Argentina)",
        "code": "56",
        "description": "ES-AR",
        "orderNumber": 57,
        "isoCode": "es-AR",
        "isoFriendlyName": "Spanish (Argentina)"
    },
    {
        "resourceId": "bcae1f7455ca",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Spanish (Chile)",
        "code": "57",
        "description": "ES-CL",
        "orderNumber": 58,
        "isoCode": "es-CL",
        "isoFriendlyName": "Spanish (Chile)"
    },
    {
        "resourceId": "8712bdda1070",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Spanish (Colombia)",
        "code": "58",
        "description": "ES-CO",
        "orderNumber": 59,
        "isoCode": "es-CO",
        "isoFriendlyName": "Spanish (Colombia)"
    },
    {
        "resourceId": "02416aff90a7",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Spanish (Mexico)",
        "code": "59",
        "description": "ES-MX",
        "orderNumber": 60,
        "isoCode": "es-MX",
        "isoFriendlyName": "Spanish (Mexico)"
    },
    {
        "resourceId": "d6bdb320d7ed",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Spanish (United States)",
        "code": "60",
        "description": "ES-US",
        "orderNumber": 61,
        "isoCode": "es-US",
        "isoFriendlyName": "Spanish (United States)"
    },
    {
        "resourceId": "f140232ad519",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "French (Belgium)",
        "code": "61",
        "description": "FR-BE",
        "orderNumber": 62,
        "isoCode": "fr-BE",
        "isoFriendlyName": "French (Belgium)"
    },
    {
        "resourceId": "b74272c4a964",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "French (Canada)",
        "code": "62",
        "description": "FR-CA",
        "orderNumber": 63,
        "isoCode": "fr-CA",
        "isoFriendlyName": "French (Canada)"
    },
    {
        "resourceId": "7f6ff12f9c60",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "French (Switzerland)",
        "code": "63",
        "description": "FR-CH",
        "orderNumber": 64,
        "isoCode": "fr-CH",
        "isoFriendlyName": "French (Switzerland)"
    },
    {
        "resourceId": "0ae3cceda777",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Italian (Switzerland)",
        "code": "64",
        "description": "IT-CH",
        "orderNumber": 65,
        "isoCode": "it-CH",
        "isoFriendlyName": "Italian (Switzerland)"
    },
    {
        "resourceId": "1019fc1f30ae",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Dutch (Belgium)",
        "code": "65",
        "description": "NL-BE",
        "orderNumber": 66,
        "isoCode": "nl-BE",
        "isoFriendlyName": "Dutch (Belgium)"
    },
    {
        "resourceId": "dd8b0e776fe0",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Portuguese (Brazil)",
        "code": "66",
        "description": "PT-BR",
        "orderNumber": 67,
        "isoCode": "pt-BR",
        "isoFriendlyName": "Portuguese (Brazil)"
    },
    {
        "resourceId": "f1422a6ccac1",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Tamil (India)",
        "code": "67",
        "description": "TA-IN",
        "orderNumber": 68,
        "isoCode": "ta-IN",
        "isoFriendlyName": "Tamil (India)"
    },
    {
        "resourceId": "0b83b6281407",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Tamil (Sri Lanka)",
        "code": "68",
        "description": "TA-LK",
        "orderNumber": 69,
        "isoCode": "ta-LK",
        "isoFriendlyName": "Tamil (Sri Lanka)"
    },
    {
        "resourceId": "ac743cd428c9",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Chinese (Hong Kong)",
        "code": "69",
        "description": "ZH-HK",
        "orderNumber": 70,
        "isoCode": "zh-HK",
        "isoFriendlyName": "Chinese (Hong Kong)"
    },
    {
        "resourceId": "1c58b9ebfaf7",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Chinese (Taiwan)",
        "code": "70",
        "description": "ZH-TW",
        "orderNumber": 71,
        "isoCode": "zh-TW",
        "isoFriendlyName": "Chinese (Taiwan)"
    },
    {
        "resourceId": "90670d5c155c",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Bulgarian (Bulgaria)",
        "code": "71",
        "description": "BG-BG",
        "orderNumber": 72,
        "isoCode": "bg-BG",
        "isoFriendlyName": "Bulgarian (Bulgaria)"
    },
    {
        "resourceId": "f5148efe6fd4",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Bosnian (Bosnia and Herzegovina)",
        "code": "72",
        "description": "BS-BA",
        "orderNumber": 73,
        "isoCode": "bs-BA",
        "isoFriendlyName": "Bosnian (Bosnia and Herzegovina)"
    },
    {
        "resourceId": "4f390739bf61",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Serbian (Serbia)",
        "code": "73",
        "description": "SR-RS",
        "orderNumber": 74,
        "isoCode": "sr-RS",
        "isoFriendlyName": "Serbian (Serbia)"
    },
    {
        "resourceId": "d4c26264572f",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Macedonian (North Macedonia)",
        "code": "74",
        "description": "MK-MK",
        "orderNumber": 75,
        "isoCode": "mk-MK",
        "isoFriendlyName": "Macedonian (North Macedonia)"
    },
    {
        "resourceId": "9094f5e9b3e6",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Latvian (Latvia)",
        "code": "75",
        "description": "LV-LV",
        "orderNumber": 76,
        "isoCode": "lv-LV",
        "isoFriendlyName": "Latvian (Latvia)"
    },
    {
        "resourceId": "a11cbb2a986d",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Lithuanian (Lithuania)",
        "code": "76",
        "description": "LT-LT",
        "orderNumber": 77,
        "isoCode": "lt-LT",
        "isoFriendlyName": "Lithuanian (Lithuania)"
    },
    {
        "resourceId": "3a0465c14965",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Estonian (Estonia)",
        "code": "77",
        "description": "ET-EE",
        "orderNumber": 78,
        "isoCode": "et-EE",
        "isoFriendlyName": "Estonian (Estonia)"
    },
    {
        "resourceId": "0f07efe334fd",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Irish (Ireland)",
        "code": "78",
        "description": "GA-IE",
        "orderNumber": 79,
        "isoCode": "ga-IE",
        "isoFriendlyName": "Irish (Ireland)"
    },
    {
        "resourceId": "6a08cc637d17",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Icelandic (Iceland)",
        "code": "79",
        "description": "IS-IS",
        "orderNumber": 80,
        "isoCode": "is-IS",
        "isoFriendlyName": "Icelandic (Iceland)"
    },
    {
        "resourceId": "efd208297590",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Maltese (Malta)",
        "code": "80",
        "description": "MT-MT",
        "orderNumber": 81,
        "isoCode": "mt-MT",
        "isoFriendlyName": "Maltese (Malta)"
    },
    {
        "resourceId": "0fa39f24d5fb",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Welsh (United Kingdom)",
        "code": "81",
        "description": "CY-GB",
        "orderNumber": 82,
        "isoCode": "cy-GB",
        "isoFriendlyName": "Welsh (United Kingdom)"
    },
    {
        "resourceId": "9368bbeb1552",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Luxembourgish (Luxembourg)",
        "code": "82",
        "description": "LB-LU",
        "orderNumber": 83,
        "isoCode": "lb-LU",
        "isoFriendlyName": "Luxembourgish (Luxembourg)"
    },
    {
        "resourceId": "36dada21fcf2",
        "genericCodeTypeId": 21,
        "genericCodeTypeName": "Language Types",
        "name": "Serbian (Bosnia and Herzegovina)",
        "code": "83",
        "description": "SR-BA",
        "orderNumber": 84,
        "isoCode": "sr-BA",
        "isoFriendlyName": "Serbian (Bosnia and Herzegovina)"
    }
]