import React from "react";

// Helper function to convert language codes to country codes
export const getCountryCode = (languageCode: string): string => {
    const languageToCountry: { [key: string]: string } = {
        'tr': 'TR',
        'en': 'US',
        'en-gb': 'GB',
        'es': 'ES',
        'es-mx': 'MX',
        'fr': 'FR',
        'de': 'DE',
        'it': 'IT',
        'pt': 'PT',
        'pt-br': 'BR',
        'ru': 'RU',
        'zh': 'CN',
        'zh-tw': 'TW',
        'ja': 'JP',
        'ko': 'KR',
        'ar': 'SA',
        'hi': 'IN',
        'bn': 'BD',
        'ur': 'PK',
        'fa': 'IR',
        'th': 'TH',
        'vi': 'VN',
        'id': 'ID',
        'ms': 'MY',
        'nl': 'NL',
        'pl': 'PL',
        'sv': 'SE',
        'da': 'DK',
        'no': 'NO',
        'fi': 'FI',
        'cs': 'CZ',
        'sk': 'SK',
        'hu': 'HU',
        'ro': 'RO',
        'bg': 'BG',
        'hr': 'HR',
        'sl': 'SI',
        'et': 'EE',
        'lv': 'LV',
        'lt': 'LT',
        'el': 'GR',
        'mt': 'MT',
        'ga': 'IE',
        'cy': 'GB',
        'eu': 'ES',
        'ca': 'ES',
        'gl': 'ES',
        'af': 'ZA',
        'sq': 'AL',
        'am': 'ET',
        'hy': 'AM',
        'az': 'AZ',
        'be': 'BY',
        'bs': 'BA',
        'ceb': 'PH',
        'ny': 'MW',
        'co': 'FR',
        'eo': 'UN',
        'tl': 'PH',
        'fy': 'NL',
        'ka': 'GE',
        'gu': 'IN',
        'ht': 'HT',
        'ha': 'NG',
        'haw': 'US',
        'iw': 'IL',
        'hmn': 'LA',
        'is': 'IS',
        'ig': 'NG',
        'jw': 'ID',
        'kn': 'IN',
        'kk': 'KZ',
        'km': 'KH',
        'ku': 'TR',
        'ky': 'KG',
        'lo': 'LA',
        'la': 'VA',
        'lb': 'LU',
        'mk': 'MK',
        'mg': 'MG',
        'ml': 'IN',
        'mi': 'NZ',
        'mr': 'IN',
        'mn': 'MN',
        'my': 'MM',
        'ne': 'NP',
        'ps': 'AF',
        'sm': 'WS',
        'gd': 'GB',
        'sr': 'RS',
        'st': 'LS',
        'sn': 'ZW',
        'sd': 'PK',
        'si': 'LK',
        'so': 'SO',
        'su': 'ID',
        'sw': 'KE',
        'tg': 'TJ',
        'ta': 'IN',
        'te': 'IN',
        'uk': 'UA',
        'uz': 'UZ',
        'xh': 'ZA',
        'yi': 'IL',
        'yo': 'NG',
        'zu': 'ZA'
    };

    return languageToCountry[languageCode] || 'UN';
};


// Helper function to detect browser language
export const detectBrowserLanguage = () => {
    if (typeof window !== 'undefined') {
        const browserLang = navigator.language || navigator.languages?.[0] || 'tr';
        return browserLang.toLowerCase().split('-')[0];
    }
    return 'tr';
};

// Custom hook for mobile detection
export const useIsMobile = () => {
    const [isMobile, setIsMobile] = React.useState(false);

    React.useEffect(() => {
        const checkIsMobile = () => {
            setIsMobile(window.innerWidth < 768);
        };

        checkIsMobile();
        window.addEventListener('resize', checkIsMobile);

        return () => window.removeEventListener('resize', checkIsMobile);
    }, []);

    return isMobile;
};

// Priority languages that appear at the top
export const priorityLanguages = [
    'tr', 'en', 'en-gb', 'es', 'fr', 'de', 'pt', 'it', 'nl', 'ru', 'zh', 'ja', 'ko', 'ar'
];

// Complete list of supported languages
export const languages = [
    { code: 'af', name: 'Afrikaans', flag: '🇿🇦' },
    { code: 'sq', name: 'Albanian', flag: '🇦🇱' },
    { code: 'am', name: 'Amharic', flag: '🇪🇹' },
    { code: 'ar', name: 'Arabic', flag: '🇸🇦' },
    { code: 'hy', name: 'Armenian', flag: '🇦🇲' },
    { code: 'az', name: 'Azerbaijani', flag: '🇦🇿' },
    { code: 'eu', name: 'Basque', flag: '🇪🇸' },
    { code: 'be', name: 'Belarusian', flag: '🇧🇾' },
    { code: 'bn', name: 'Bengali', flag: '🇧🇩' },
    { code: 'bs', name: 'Bosnian', flag: '🇧🇦' },
    { code: 'bg', name: 'Bulgarian', flag: '🇧🇬' },
    { code: 'ca', name: 'Catalan', flag: '🇪🇸' },
    { code: 'ceb', name: 'Cebuano', flag: '🇵🇭' },
    { code: 'ny', name: 'Chichewa', flag: '🇲🇼' },
    { code: 'zh', name: 'Chinese (Simplified)', flag: '🇨🇳' },
    { code: 'zh-tw', name: 'Chinese (Traditional)', flag: '🇹🇼' },
    { code: 'co', name: 'Corsican', flag: '🇫🇷' },
    { code: 'hr', name: 'Croatian', flag: '🇭🇷' },
    { code: 'cs', name: 'Czech', flag: '🇨🇿' },
    { code: 'da', name: 'Danish', flag: '🇩🇰' },
    { code: 'nl', name: 'Dutch', flag: '🇳🇱' },
    { code: 'en', name: 'English', flag: '🇺🇸' },
    { code: 'en-gb', name: 'English (UK)', flag: '🇬🇧' },
    { code: 'eo', name: 'Esperanto', flag: '🌍' },
    { code: 'et', name: 'Estonian', flag: '🇪🇪' },
    { code: 'tl', name: 'Filipino', flag: '🇵🇭' },
    { code: 'fi', name: 'Finnish', flag: '🇫🇮' },
    { code: 'fr', name: 'French', flag: '🇫🇷' },
    { code: 'fy', name: 'Frisian', flag: '🇳🇱' },
    { code: 'gl', name: 'Galician', flag: '🇪🇸' },
    { code: 'ka', name: 'Georgian', flag: '🇬🇪' },
    { code: 'de', name: 'German', flag: '🇩🇪' },
    { code: 'el', name: 'Greek', flag: '🇬🇷' },
    { code: 'gu', name: 'Gujarati', flag: '🇮🇳' },
    { code: 'ht', name: 'Haitian Creole', flag: '🇭🇹' },
    { code: 'ha', name: 'Hausa', flag: '🇳🇬' },
    { code: 'haw', name: 'Hawaiian', flag: '🇺🇸' },
    { code: 'iw', name: 'Hebrew', flag: '🇮🇱' },
    { code: 'hi', name: 'Hindi', flag: '🇮🇳' },
    { code: 'hmn', name: 'Hmong', flag: '🇱🇦' },
    { code: 'hu', name: 'Hungarian', flag: '🇭🇺' },
    { code: 'is', name: 'Icelandic', flag: '🇮🇸' },
    { code: 'ig', name: 'Igbo', flag: '🇳🇬' },
    { code: 'id', name: 'Indonesian', flag: '🇮🇩' },
    { code: 'ga', name: 'Irish', flag: '🇮🇪' },
    { code: 'it', name: 'Italian', flag: '🇮🇹' },
    { code: 'ja', name: 'Japanese', flag: '🇯🇵' },
    { code: 'jw', name: 'Javanese', flag: '🇮🇩' },
    { code: 'kn', name: 'Kannada', flag: '🇮🇳' },
    { code: 'kk', name: 'Kazakh', flag: '🇰🇿' },
    { code: 'km', name: 'Khmer', flag: '🇰🇭' },
    { code: 'ko', name: 'Korean', flag: '🇰🇷' },
    { code: 'ku', name: 'Kurdish (Kurmanji)', flag: '🇹🇷' },
    { code: 'ky', name: 'Kyrgyz', flag: '🇰🇬' },
    { code: 'lo', name: 'Lao', flag: '🇱🇦' },
    { code: 'la', name: 'Latin', flag: '🇻🇦' },
    { code: 'lb', name: 'Luxembourgish', flag: '🇱🇺' },
    { code: 'mk', name: 'Macedonian', flag: '🇲🇰' },
    { code: 'mg', name: 'Malagasy', flag: '🇲🇬' },
    { code: 'ms', name: 'Malay', flag: '🇲🇾' },
    { code: 'ml', name: 'Malayalam', flag: '🇮🇳' },
    { code: 'mt', name: 'Maltese', flag: '🇲🇹' },
    { code: 'mi', name: 'Maori', flag: '🇳🇿' },
    { code: 'mr', name: 'Marathi', flag: '🇮🇳' },
    { code: 'mn', name: 'Mongolian', flag: '🇲🇳' },
    { code: 'my', name: 'Myanmar (Burmese)', flag: '🇲🇲' },
    { code: 'ne', name: 'Nepali', flag: '🇳🇵' },
    { code: 'ps', name: 'Pashto', flag: '🇦🇫' },
    { code: 'sm', name: 'Samoan', flag: '🇼🇸' },
    { code: 'gd', name: 'Scots Gaelic', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
    { code: 'sr', name: 'Serbian', flag: '🇷🇸' },
    { code: 'st', name: 'Sesotho', flag: '🇱🇸' },
    { code: 'sd', name: 'Sindhi', flag: '🇵🇰' },
    { code: 'si', name: 'Sinhala', flag: '🇱🇰' },
    { code: 'sk', name: 'Slovak', flag: '🇸🇰' },
    { code: 'sl', name: 'Slovenian', flag: '🇸🇮' },
    { code: 'so', name: 'Somali', flag: '🇸🇴' },
    { code: 'es', name: 'Spanish', flag: '🇪🇸' },
    { code: 'es-mx', name: 'Spanish (Mexico)', flag: '🇲🇽' },
    { code: 'su', name: 'Sundanese', flag: '🇮🇩' },
    { code: 'sw', name: 'Swahili', flag: '🇰🇪' },
    { code: 'sv', name: 'Swedish', flag: '🇸🇪' },
    { code: 'tg', name: 'Tajik', flag: '🇹🇯' },
    { code: 'ta', name: 'Tamil', flag: '🇮🇳' },
    { code: 'te', name: 'Telugu', flag: '🇮🇳' },
    { code: 'th', name: 'Thai', flag: '🇹🇭' },
    { code: 'tr', name: 'Turkish', flag: '🇹🇷' },
    { code: 'uk', name: 'Ukrainian', flag: '🇺🇦' },
    { code: 'ur', name: 'Urdu', flag: '🇵🇰' },
    { code: 'uz', name: 'Uzbek', flag: '🇺🇿' },
    { code: 'vi', name: 'Vietnamese', flag: '🇻🇳' },
    { code: 'cy', name: 'Welsh', flag: '🇬🇧' },
    { code: 'xh', name: 'Xhosa', flag: '🇿🇦' },
    { code: 'yi', name: 'Yiddish', flag: '🇮🇱' },
    { code: 'yo', name: 'Yoruba', flag: '🇳🇬' },
    { code: 'zu', name: 'Zulu', flag: '🇿🇦' }
]; 